##项目启动端口,默认8080
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 819
  servlet:
    context-path: /wechat/persistence

logging:
  config: classpath:log4j2.xml
  path: ./logs



spring:

  application:
    name: wx-msg-persistence

  aop:
    auto: true
    proxy-target-class: false
  datasource:
    url: jdbc:mysql://119.3.24.108:9001/wechat_msg?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: wechat_msg
    password: j8G&L4G^J9ui6789
#    password: wechat_msg
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化连接池的连接数量 大小，最小，最大
      initial-size: 10
      min-idle: 5
      max-active: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      ## 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      log-abandoned: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      # 是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 100000
        # 你可以配置principalSessionName，使得druid能够知道当前的session的用户是谁=admin
        principal-session-name: admin
        principal-cookie-name: admin
        profile-enable: true

      stat-view-servlet:
        # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 设置不统计哪些URL
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
      aop-patterns: com.atmatrix.wechat.application.*,com.atmatrix.wechat.infrastructure.dao.*,com.atmatrix.wechat.controller.*
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
  security:
    user:
      name: admin
      password: admin
      roles: ACTUATOR_ADMIN
  kafka:
    bootstrap-servers: 119.3.44.28:9092,119.3.47.237:9092,119.3.40.178:9092,119.3.42.210:9092
    template:
      default-topic:
    listener:
      concurrency: 3
    consumer:
      group-id: wx_msg_10
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-request-size: 10MB
      max-file-size: 8MB


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

    health-check-url-path: http://${eureka.instance.ip-address}:${server.port}${server.servlet.context-path}/actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}${server.servlet.context-path}/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}${server.servlet.context-path}
    ip-address: 127.0.0.1
    prefer-ip-address: true

  client:
    registryFetchIntervalSeconds: 30
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://47.110.251.61:8761}/eureka/
#      defaultZone: ${EUREKA_SERVICE_URL:http://127.0.0.1:8761}/eureka/
    eureka-server-u-r-l-context: /wechat/euraka
    eureka-server-port: 8761




# actuator
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

mybatis:
  # 扫描classpath下mapper目录下的所有.xml文件
  mapper-locations: classpath:mapper/*.xml
  # 实体类的包路径
  type-aliases-package: com.atmatrix.wechat.infrastructure.po
  # 开启驼峰匹配
  configuration:
    map-underscore-to-camel-case: true




#spring.aop.proxy-target-class=false