version: '3'
services:
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
    - ./app:/app
    - ~/.m2:/root/.m2
    expose:
    - "4111"
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker

